import Head from "next/head";
import Image from "next/image";

export default function Home(){
    return (
        <div>
            <Head>
                <title>Cek Cuaca</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
        <div className="container">
        <div className="row mt-5">
            <div className="col">
                <h2 className="header">Cek Cuaca Hari Ini</h2>
            <br/>
            </div>
        </div> 

        <div >
            <div className="col-md-8">
                <div className="input-group mb-3">
                    <input type="text" className="form-control input-keyword" placeholder="Ketik Kota" aria-label="Recipient's username" aria-describedby="button-addon2"/>
                    
                    <button className="save" type="button" id="button-addon2">Search</button>
                </div>
            </div>
        </div>
    </div>
    <br/><br/>
    <div className="container mt-5 result">
	  </div>
      
    {/* <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
    <script src="../js/script.js"></script>   */}
        </div>
    );
}

// export async function getStaticProps() {
// return{
//   props: {
//     dataUsers: [],
//   },
// };

// }
